service: slack-issue-helper-hello-world
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  region: ap-northeast-2
  timeout: 60
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
        - "sqs:GetQueueUrl"
      Resource: "arn:aws:sqs:${self:provider.region}:173249517772:MyQueue"
    - Effect: "Allow"
      Action:
        - "sqs:ListQueues"
      Resource: "arn:aws:sqs:${self:provider.region}:173249517772:*"
  environment:
    TZ: Asia/Seoul

functions:
  sender:
    handler: src/sender.server
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
  receiver:
    handler: src/receiver.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn

resources:
  Resources:
    MyQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "MyQueue"
        MessageRetentionPeriod: 120

useDotenv: true

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true
  esbuild:
    bundle: true
