service: slack-issue-maker
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  region: ap-northeast-2
  timeout: 60
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
        - "sqs:GetQueueUrl"
      Resource: !Sub "arn:aws:sqs:${self:provider.region}:${AWS::AccountId}:SlackQueue"
    - Effect: "Allow"
      Action:
        - "sqs:ListQueues"
      Resource: !Sub "arn:aws:sqs:${self:provider.region}:${AWS::AccountId}:*"
  environment:
    TZ: Asia/Seoul

functions:
  sender:
    handler: src/sender.server
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
  receiver:
    handler: src/receiver.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - SlackQueue
              - Arn

resources:
  Resources:
    SlackQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "SlackQueue"
        VisibilityTimeout: 120
        MessageRetentionPeriod: 120

useDotenv: true

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true
  esbuild:
    bundle: true
